### ISSUE TITLE
Issue with Active Dashboard Tab in created team

### ISSUE THREAD

**Issue by ssmmarkelbert1** [OfficeDev/microsoft-teams-emergency-operations-center#318]
I have an issue where the Active Dashboard tab created when the Team gets created gives an error it cant reach the app.  

![Image](https://github.com/user-attachments/assets/d75519b3-1d8c-420b-9ddd-34485a9e9949)

Also is there anyone to help with just confirming the setup is correct?  

Thank you

**Comment by ssmmarkelbert1** [comment]
using teoc version 3.3

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 , thanks for bringing this to our attention.
I believe you can access the TEOC app and create Incidents, but you cannot access the Active Dashboard Tab. To troubleshoot this, did you update the ID in the manifest file you uploaded to the Teams Admin center? Please share the manifest file so we can guide you. Also, check if you have provided all the necessary permissions to the Azure AD App.
For more information, refer to this link: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#5-add-permissions-to-microsoft-graph-azure-ad-app
Additionally, to check if your deployment was successful, navigate to the Azure Resource Group, click on deployment from the left pane, and see if all items show success. Please share that screenshot as well.

**Comment by ssmmarkelbert1** [comment]
[SSMHealthTEOC3.zip](https://github.com/user-attachments/files/18645114/SSMHealthTEOC3.zip)  Manifest file located in zip file thank you for your help!!!  Can we schedule a call or something?

**Comment by ssmmarkelbert1** [comment]
I think i may have messed up one part but wanted to confirm.  

![Image](https://github.com/user-attachments/assets/c43f1cdd-4d01-4b2d-b92f-263848e1c3a0)

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 ,
Thanks for sharing the manifest file.
You have updated the Teams ID while updating the Manifest file. To resolve this issue, please download the Manifest file and update only the section we highlighted or mentioned in the document. Then, remove the existing app from the Teams Admin center and upload the zip file containing the updated Manifest file. This should resolve the issue.
Refer this link for more information - https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages
I'm closing this issue. However, if you face any problems or have any questions, please feel free to post them here.
<img width="590" alt="Image" src="https://github.com/user-attachments/assets/70166d81-7980-4c51-bc43-bd0c465365cc" />

**Comment by ssmmarkelbert1** [comment]
i am confused.  that is already set in the manifest i sent you.  Are you saying download a fresh one from the site and then only change that field?  What about all the setting referenced in the document?

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 ,
You need to download the manifest file from the repo and update it with your app domain, website URL, and client ID.
Below is the screenshot for the Team App ID, which you updated with the client ID.

![Image](https://github.com/user-attachments/assets/56d23e2f-a8ed-48ed-ab04-91c31162241f)

**Comment by ssmmarkelbert1** [comment]
This is not fixed and the steps provided in the document have already been done and reflected in the manifest.json that was requested to be uploaded.  Please reopen incident

**Comment by ssmmarkelbert1** [comment]
how about 7:00 am central time which would be 6:30 pm IST Time if my converter is correct. I am free Monday the 2/10/25 or any day after.  Thank you very much!!!!

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 ,
Thank you for sharing your availability. Please provide your email address as well so that I can schedule a call with you. Make sure to share it directly here on GitHub; if you share it through email, we won't be able to view it.

**Comment by ssmmarkelbert1** [comment]
Good day.  My email address for the meeting is mark.elbert@ssmhealth.com.  Thank you very much!!!!

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 ,
I have scheduled a meeting on 2/10/25 at 6:30 PM IST to address the issue you are experiencing with the TEOC application.

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 ,
As per our conversation in the meeting, please update the Teams App ID to its previous value. Additionally, remove the app from the Teams Admin Center and upload the zip file containing the updated manifest. This should resolve the issue.
I'm closing this issue. However, if you have any queries or issues, please feel free to post them here.

**Comment by v-ajaysahu** [comment]
@ssmmarkelbert1 ,
No, you cannot run two versions in the same environment because the Teams App ID is the same. The Teams Admin Center won't allow the app upload since an app with the same ID already exists.
